require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: True
  CountComments: false
  Max: 20

Lint/AmbiguousBlockAssociation:
  Enabled: false

