require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/ExampleLength:
  Enabled: true
  Max: 15

Metrics/BlockLength:
  Enabled: false
