AllCops:
  TargetRubyVersion: 2.7
  Include:
    - lib/**/*.rb
    - Gemfile
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: True
  CountComments: false
  Max: 20

