require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
      - lib/theme_park/blackjack/game.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/NestedGroup:
  Enabled: true
  Max: 4

RSpec/ExampleLength:
  Enabled: true
  Max: 15

Metrics/BlockLength:
  Enabled: false
